export const LOCATIONS = [
  "Short arm cast - left",
  "Short arm cast - right",
  "Long arm cast - left",
  "Long arm cast - right",
  "Short leg cast - left",
  "Short leg cast - right",
  "Long leg cast - left",
  "Long leg cast - right",
  "Sacrum",
  "Occiput",
  "Heel - left",
  "Heel - right",
  "Other",
];
