import {useEffect,useState} from 'react';
import {ScrollView,View,Text,Pressable} from 'react-native';
import Svg,{Path,Line,Text as SvgText} from 'react-native-svg';
import {api,type Readings} from '../api';
import {Card,H,Soft,Button,ErrorText} from '../ui';
import {c} from '../theme';
const colors=['#ad91ff','#ff83b0','#63d5ea','#ffcb6b'];
const windows=[{label:'10m',minutes:10},{label:'1h',minutes:60},{label:'3h',minutes:180},{label:'1d',minutes:1440}];
export default function History({id}:{id:number}) {
 const [win,setWin]=useState(windows[1]);const [segment,setSegment]=useState(30);const [data,setData]=useState<Readings|null>(null);const [err,setErr]=useState('');const [tick,setTick]=useState(0);
 useEffect(()=>{let alive=true;setData(null);api.readings(id,win.minutes,segment).then(d=>{if(alive){setData(d);setErr('')}}).catch(e=>{if(alive)setErr(e.message)});return()=>{alive=false}},[id,win,segment,tick]);
 const points=data?.chart??[];const from=points[0]?.t??0;const to=points.at(-1)?.t??1;const max=Math.max(40,...points.flatMap(p=>p.z));
 function line(zone:number){let path='';points.forEach((p,i)=>{const x=35+(p.t-from)/Math.max(1,to-from)*290;const y=175-p.z[zone]/max*150;path+=`${!i||p.t-points[i-1].t>15000?'M':'L'}${x.toFixed(1)} ${y.toFixed(1)} `});return path}
 return <ScrollView contentContainerStyle={{padding:16,paddingBottom:32}}><H>Historical pressure</H><View style={{flexDirection:'row',gap:6,marginBottom:14}}>{windows.map(w=><Pressable key={w.label} onPress={()=>setWin(w)} accessibilityRole="button" accessibilityState={{selected:w===win}} style={{padding:10,borderRadius:8,backgroundColor:w===win?'#23465e':c.card}}><Text style={{color:c.text}}>{w.label}</Text></Pressable>)}</View><ErrorText>{err}</ErrorText><Card><H>Pressure trend · mmHg</H>{points.length?<><Svg viewBox="0 0 350 215" width="100%" height={215}>{[0,.5,1].map(v=><ReactGrid key={v} y={175-v*150} label={String(Math.round(v*max))}/>)}{[0,1,2,3].map(k=><Path key={k} d={line(k)} fill="none" stroke={colors[k]} strokeWidth={1.4}/>)}<SvgText x={35} y={202} fill={c.soft} fontSize={10}>{new Date(from).toLocaleTimeString()}</SvgText><SvgText x={325} y={202} fill={c.soft} textAnchor="end" fontSize={10}>{new Date(to).toLocaleTimeString()}</SvgText></Svg><View style={{flexDirection:'row',justifyContent:'space-between'}}>{colors.map((color,i)=><Text key={i} style={{color,fontSize:12}}>Zone {i+1}</Text>)}</View></>:<Soft>{data?'No pressure data in this window.':'Loading…'}</Soft>}</Card><Card><H>Segment history</H><Soft>Segment duration</Soft><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[30,60,300,1800].map(s=><Button key={s} title={s<60?`${s}s`:`${s/60}m`} kind={s===segment?'primary':'plain'} onPress={()=>setSegment(s)}/>)}</View><ScrollView horizontal><View style={{flexDirection:'row',gap:3,paddingVertical:10}}>{data?.segments.map(s=><View key={s.start} style={{gap:3}}>{s.status.map((st,i)=><View key={i} accessibilityLabel={`Zone ${i+1}, ${new Date(s.start).toLocaleTimeString()}, ${st}, ${s.mean[i]??'no data'}`} style={{width:12,height:12,borderRadius:6,backgroundColor:st==='ok'?c.ok:st==='high'?c.high:st==='low'?c.low:c.none}}/>)}</View>)}</View></ScrollView><Soft>Rows Z1–Z4 · green within target, red high, blue low, grey missing. These are segment averages, not exposure alerts.</Soft></Card><Card><H>Recent measurements</H>{data?.recent.map(p=><View key={p.t} style={{paddingVertical:6,borderBottomWidth:1,borderColor:c.line}}><Soft>{new Date(p.t).toLocaleTimeString()}</Soft><Text style={{color:c.text,fontVariant:['tabular-nums']}}>{p.z.map((v,i)=>`Z${i+1} ${Math.round(v)}`).join('  ·  ')} mmHg</Text></View>)}{data&&!data.recent.length&&<Soft>No readings.</Soft>}</Card><Button title="Refresh history" kind="plain" onPress={()=>setTick(t=>t+1)}/></ScrollView>;
}
function ReactGrid({y,label}:{y:number;label:string}){return <><Line x1={35} x2={325} y1={y} y2={y} stroke={c.line}/><SvgText x={28} y={y+4} textAnchor="end" fill={c.soft} fontSize={10}>{label}</SvgText></>}
