import {useEffect,useState} from 'react';
import {Alert,Pressable,ScrollView,Text,View} from 'react-native';
import {scan,SIMULATED,type Found} from '../module';
import {api,type PatientSummary} from '../api';
import {useLive} from '../store';
import {Button,Card,ErrorText,H,Soft} from '../ui';
import {c} from '../theme';
export default function Modules({patientId,patientName,onBack,onPatient,readOnly=false}:{readOnly?:boolean;patientId?:number;patientName?:string;onBack():void;onPatient(id:number):void}){
 const live=useLive();const [found,setFound]=useState<Found[]>([]);const [selected,setSelected]=useState<Found|null>(null);const [pid,setPid]=useState(patientId??null);const [patients,setPatients]=useState<PatientSummary[]>([]);const [scanning,setScanning]=useState(false);const [connecting,setConnecting]=useState(false);const [err,setErr]=useState('');
 useEffect(()=>{api.patients().then(setPatients).catch(e=>setErr(e.message))},[]);
 async function startScan(){setErr('');setFound([]);setScanning(true);try{await scan(d=>setFound(f=>f.some(x=>x.id===d.id)?f:[...f,d]))}catch(e){setErr(e instanceof Error?e.message:'Scan failed')}finally{setScanning(false)}}
 async function connect(){if(!selected||!pid||connecting)return;setConnecting(true);setErr('');try{await live.connect(selected,pid);setSelected(null)}catch(e){setErr(e instanceof Error?e.message:'Could not connect')}finally{setConnecting(false)}}
 const latest=live.latest&&Date.now()-live.latest.t<10000?live.latest:null;
 return <ScrollView contentContainerStyle={{padding:16,paddingBottom:32}}><H>{selected?selected.name:'Manage devices'}</H><ErrorText>{err}</ErrorText>{selected?<><Card><H>Assign patient</H><Soft>{selected.simulated?'Simulated device for testing':'Confirm the intended patient before connecting.'}</Soft>{patients.map(p=><Pressable key={p.id} accessibilityRole="radio" accessibilityState={{checked:pid===p.id}} onPress={()=>setPid(p.id)} disabled={connecting} style={{padding:12,borderRadius:8,backgroundColor:pid===p.id?'#23465e':c.card}}><Text style={{color:c.text}}>{pid===p.id?'● ':'○ '}{p.firstName} {p.lastName}{p.mrn?` · MRN ${p.mrn}`:''}</Text></Pressable>)}{patientId&&!patients.some(p=>p.id===patientId)&&<Soft>{patientName}</Soft>}<Button title="Assign and connect device" onPress={connect} busy={connecting} disabled={!pid}/><Button title="Back to devices" kind="plain" onPress={()=>setSelected(null)} disabled={connecting}/></Card></>:<><Card><H>Connected device</H>{live.connection?<><Soft>{live.connection.name} · Battery {live.connection.battery??'–'}%</Soft><Soft>Assigned patient ID {live.patientId}</Soft>{[1,2,3,4].map((z,i)=><Soft key={z}>Zone {z}: {latest?Math.round(latest.z[i]):'–'} mmHg</Soft>)}<Button title="Open patient live readings" onPress={()=>live.patientId&&onPatient(live.patientId)}/><Button title="Disconnect device" kind="danger" onPress={()=>Alert.alert('Disconnect device?','Live readings stop until you reconnect.',[{text:'Cancel',style:'cancel'},{text:'Disconnect',style:'destructive',onPress:()=>live.disconnect().catch(e=>setErr(e.message))}])}/></>:<Soft>No device connected.</Soft>}</Card><Card><H>Discovered devices</H><Button title={scanning?'Searching…':'Search for modules'} busy={scanning} onPress={startScan}/>{[...found,SIMULATED].filter(d=>!readOnly||patients.some(p=>p.deviceId===d.name)).map(d=><Pressable key={d.id} onPress={()=>setSelected(d)} accessibilityRole="button" style={{paddingVertical:16,borderBottomWidth:1,borderColor:c.line}}><Text style={{color:c.text,fontWeight:'700'}}>{d.name} ›</Text><Soft>{d.simulated?'Simulated module · no hardware needed':`Signal ${d.rssi??'–'} dBm`}</Soft></Pressable>)}{!found.length&&!scanning&&<Soft>{readOnly?"Only the module assigned by your clinician can be connected. Turn it on, then search.":"Turn on the module, then search."}</Soft>}</Card></>}</ScrollView>;
}
