import {useEffect,useState,useRef} from 'react';
import {Alert,Text,View,Pressable} from 'react-native';
import {api} from '../api';
import {Button,Card,H,Soft,ErrorText} from '../ui';
import {Field,FormPage} from '../forms';
import {c,LOCATIONS} from '../theme';
import {emptyDraft,validateDetails,validateRanges,payload,type PatientDraft,type RangeDraft} from '../onboarding';
const STEPS=['Patient details','Sensor setup','Review','Ready'];
export default function Onboarding({id,onCancel,onDone,onConnect,onInvite}:{id?:number;onCancel():void;onDone(id:number):void;onInvite(id:number):void;onConnect(id:number,name:string):void}) {
 const [draft,setDraft]=useState<PatientDraft>({...emptyDraft});const [ranges,setRanges]=useState<RangeDraft[]>([1,2,3,4].map(zone=>({zone,min:'0',max:'30'})));const [step,setStep]=useState(0);const [busy,setBusy]=useState(!!id);const [error,setError]=useState('');const [ready,setReady]=useState(!id);const [saved,setSaved]=useState<number|null>(null); const saving=useRef(false);
 useEffect(()=>{if(id)api.patient(id).then(p=>{setDraft({firstName:p.firstName,lastName:p.lastName,mrn:p.mrn??'',dob:p.dob??'',sex:p.sex??'',email:p.email??'',sensorLocation:p.sensorLocation??'',heightCm:p.heightCm?.toString()??'',weightKg:p.weightKg?.toString()??''});setRanges([1,2,3,4].map(zone=>{const t=p.thresholds.find(t=>t.zone===zone);return {zone,min:String(t?.min??0),max:String(t?.max??30)}}));setReady(true)}).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[id]);
 const change=(key:keyof PatientDraft)=>(v:string)=>setDraft(d=>({...d,[key]:v}));
 function next(){const e=step===0?validateDetails(draft):!draft.sensorLocation?'Choose the sensor location.':validateRanges(ranges);setError(e);if(!e)setStep(s=>s+1);}
 async function save(){if(saving.current)return;const e=validateDetails(draft)||validateRanges(ranges)||(!draft.sensorLocation?'Choose the sensor location.':'');if(e)return setError(e);saving.current=true;setBusy(true);setError('');try {const body=payload(draft,ranges);let pid=id;if(pid)await api.save(pid,body);else pid=(await api.create(body)).id;setSaved(pid);setStep(3);}catch(e){setError(e instanceof Error?e.message:'Could not save patient.')}finally{saving.current=false;setBusy(false)}}
 function cancel(){if(step===3)return onDone(saved!);Alert.alert('Leave onboarding?','Unsaved changes will be discarded.',[{text:'Keep editing',style:'cancel'},{text:'Leave',onPress:onCancel}]);}
 return <FormPage><Button title={step===3?'Close':'Cancel'} kind="plain" onPress={cancel} disabled={busy}/><Text style={{color:c.text,fontSize:26,fontWeight:'700',marginVertical:16}}>{id?'Edit patient':'Onboard a patient'}</Text><View style={{flexDirection:'row',gap:5,marginBottom:18}}>{STEPS.map((_,i)=><View key={i} style={{height:4,flex:1,backgroundColor:i<=step?c.accent:c.line,borderRadius:3}}/>)}</View><H>{step+1} / 4 · {STEPS[step]}</H><ErrorText>{error}</ErrorText>
 {step===0&&<Card><Field label="First name *" value={draft.firstName} onChange={change('firstName')}/><Field label="Last name *" value={draft.lastName} onChange={change('lastName')}/><Field label="MRN" value={draft.mrn} onChange={change('mrn')}/><Field label="Date of birth (YYYY-MM-DD)" value={draft.dob} onChange={change('dob')}/><Field label="Sex / gender" value={draft.sex} onChange={change('sex')}/><Field label="Patient email (optional)" value={draft.email} onChange={change('email')}/><Field label="Height (cm)" value={draft.heightCm} onChange={change('heightCm')} number/><Field label="Weight (kg)" value={draft.weightKg} onChange={change('weightKg')} number/></Card>}
 {step===1&&<><Card><H>Sensor location</H>{LOCATIONS.map(l=><Pressable key={l} onPress={()=>change('sensorLocation')(l)} accessibilityRole="radio" accessibilityState={{checked:draft.sensorLocation===l}} style={{padding:12,borderRadius:8,backgroundColor:draft.sensorLocation===l?'#23465e':c.card}}><Text style={{color:draft.sensorLocation===l?c.accent:c.text}}>{draft.sensorLocation===l?'● ':'○ '}{l}</Text></Pressable>)}</Card><Card><H>Clinician pressure ranges</H><Soft>Review each range for this patient. These settings apply to app/server alerts; module synchronization is pending.</Soft>{ranges.map((t,i)=><View key={t.zone} style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Field label={`Z${t.zone} minimum (mmHg)`} value={t.min} number onChange={v=>setRanges(r=>r.map((x,k)=>k===i?{...x,min:v}:x))}/></View><View style={{flex:1}}><Field label={`Z${t.zone} maximum (mmHg)`} value={t.max} number onChange={v=>setRanges(r=>r.map((x,k)=>k===i?{...x,max:v}:x))}/></View></View>)}</Card></>}
 {step===2&&<Card><H>{draft.firstName} {draft.lastName}</H><Soft>{draft.mrn?`MRN ${draft.mrn}`:'MRN not supplied'}</Soft><Soft>{draft.dob||'Date of birth not supplied'}</Soft><Soft>{draft.email||'Email not supplied'}</Soft><Soft>{draft.sensorLocation}</Soft>{ranges.map(t=><Soft key={t.zone}>Zone {t.zone}: {t.min}–{t.max} mmHg</Soft>)}<Soft>Save the patient record first, then invite the patient to create an account.</Soft></Card>}
 {step===3&&<Card><H>Patient saved</H><Soft>Connect a module, then capture the initial baseline from Live readings.</Soft><Button title="Connect a module" onPress={()=>onConnect(saved!,`${draft.firstName} ${draft.lastName}`)}/><Button title="Invite patient to sign in" kind="plain" onPress={()=>onInvite(saved!)}/><Button title="Open patient" kind="plain" onPress={()=>onDone(saved!)}/></Card>}
 {step<3&&<View style={{gap:10}}>{step>0&&<Button title="Previous" kind="plain" onPress={()=>{setError('');setStep(s=>s-1)}} disabled={busy}/>}<Button title={step===2?'Save patient':'Continue'} onPress={step===2?save:next} busy={busy} disabled={!ready}/></View>}
 </FormPage>;
}
