import {useEffect,useState} from 'react';
import {ScrollView,Text} from 'react-native';
import {api,type Patient} from '../api';
import {Card,H,Soft,Button,ErrorText} from '../ui';
export default function PatientDetails({id,onEdit,onConnect,onLive,onInvite,readOnly=false}:{id:number;onEdit():void;onConnect(name:string):void;onLive():void;onInvite():void;readOnly?:boolean}) {
 const [patient,setPatient]=useState<Patient|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;api.patient(id).then(p=>{if(active)setPatient(p)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id]);
 return <ScrollView contentContainerStyle={{padding:16,paddingBottom:32}}><ErrorText>{error}</ErrorText>{patient?<><Card><H>{patient.firstName} {patient.lastName}</H><Soft>Patient ID {patient.id}</Soft><Soft>MRN: {patient.mrn||'Not assigned'}</Soft><Soft>DOB: {patient.dob||'Not recorded'}</Soft><Soft>Sex / gender: {patient.sex||'Not recorded'}</Soft><Soft>Height: {patient.heightCm??'–'} cm · Weight: {patient.weightKg??'–'} kg</Soft><Soft>Email: {patient.email||'Not recorded'}</Soft>{!readOnly&&<Button title="Edit details and sensor setup" kind="plain" onPress={onEdit}/>}</Card><Card><H>Monitoring setup</H><Soft>{patient.sensorLocation||'Sensor location not selected'}</Soft>{patient.thresholds.map(t=><Soft key={t.zone}>Zone {t.zone}: {t.min}–{t.max} mmHg</Soft>)}<Soft>Module: {patient.device?.id||'Not assigned'}</Soft><Soft>Baseline: {patient.baseline?new Date(patient.baseline.capturedAt).toLocaleString():'Not captured'}</Soft><Button title="Connect / manage module" onPress={()=>onConnect(`${patient.firstName} ${patient.lastName}`)}/><Button title="Live readings" kind="plain" onPress={onLive}/></Card><Card><H>Patient access</H><Soft>Your clinician manages the sensor configuration. Patient accounts can access only their own record.</Soft>{!readOnly&&<Button title="Invite patient / account status" onPress={onInvite}/>}</Card></>:!error&&<Soft>Loading patient…</Soft>}</ScrollView>;
}
