import {useCallback,useEffect,useRef,useState} from 'react';
import {api,type RecordEntry} from '../api';
import {Button,Card,H,Soft,ErrorText} from '../ui';
import {Field,FormPage} from '../forms';
export default function Records({id,kind}:{id:number;kind:'notes'|'encounters'}) {
 const [records,setRecords]=useState<RecordEntry[]>([]);const [body,setBody]=useState('');const [title,setTitle]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const saving=useRef(false);
 const load=useCallback(async()=>{try{setRecords(await api.records(id,kind));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load records')}},[id,kind]);useEffect(()=>{load()},[load]);
 async function add(){if(saving.current)return;if(kind==='notes'&&!body.trim())return setError('Enter a note.');if(kind==='encounters'&&!title.trim())return setError('Enter an encounter title.');const occurred=new Date(date+'T12:00:00Z');if(kind==='encounters'&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(occurred.getTime())||occurred.toISOString().slice(0,10)!==date))return setError('Enter a valid date as YYYY-MM-DD.');saving.current=true;setBusy(true);try{await api.addRecord(id,kind,kind==='notes'?{body}:{title,body,occurredAt:occurred.toISOString()});setBody('');setTitle('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not save entry')}finally{saving.current=false;setBusy(false)}}
 return <FormPage><H>{kind==='notes'?'Notes':'Encounters'}</H><Soft>{kind==='notes'?'Clinician observations saved with author and timestamp.':'Manually recorded encounters. Epic synchronization is not connected.'}</Soft><ErrorText>{error}</ErrorText><Card>{kind==='encounters'&&<><Field label="Encounter title" value={title} onChange={setTitle}/><Field label="Encounter date (YYYY-MM-DD)" value={date} onChange={setDate}/></>}<Field label={kind==='notes'?'New note':'Encounter details'} value={body} onChange={setBody} multiline/><Button title={kind==='notes'?'Save note':'Save encounter'} busy={busy} onPress={add}/></Card>{records.map(r=><Card key={r.id}><H>{r.title||'Clinician note'}</H><Soft>{new Date(r.occurredAt||r.createdAt).toLocaleDateString()} · {r.author}</Soft><Soft>{r.body}</Soft></Card>)}{!records.length&&!error&&<Soft>No entries yet.</Soft>}<Button title="Refresh" kind="plain" onPress={load}/></FormPage>;
}
