"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
export default function Login(){
 const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [remember,setRemember]=useState(false);const [err,setErr]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setErr("");try{const res=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,remember})});const data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error??"Sign-in failed.");router.replace("/patients");router.refresh()}catch(e){setErr(e instanceof Error?e.message:"Could not connect. Try again.")}finally{setBusy(false)}}
 return <main className="loginwrap auth-background"><form className="login" onSubmit={submit}><h1>Welcome to CastLiner</h1><p className="muted">Please sign in to your account.</p><label>Email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="auth-options"><label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember me</label><Link href="/forgot-password">Forgot your password?</Link></div>{err&&<p className="error" role="alert">{err}</p>}<button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button><p className="muted">Need an account? Ask your organization administrator for access. Patient accounts use an invitation from a clinician.</p><a className="demo-entry" href="/demo/index.html">Try demo — no login required</a><small className="muted">Fictional patients and synthetic readings. Demo changes stay in this browser.</small></form></main>
}
